### ISSUE TITLE
Link from bitstruct readme

### ISSUE THREAD

**Issue by eerimoq** [peterzuger/bitstruct-micropython#1]
Nice job porting the bitstruct C implementation to Micropython!

Would you mind if I add a link to this repository in the bitstruct readme, just to make it easier to find?

**Comment by peterzuger** [comment]
Thanks, it was not much, I just took your code and adapted it.

Sure, it would be great to have a few more people take a look at it.

**Comment by eerimoq** [comment]
Link added.
